image:

environment:
  matrix:
    - image: Visual Studio 2019
      asNuget: nuget
    - image: Ubuntu1604
      asNuget: nuget
      BuildFrameWorks: netstandard2.0
    - image: macos
      asNuget: dotnet
      BuildFrameWorks: netstandard2.0
    - image: macos-mojave
      asNuget: dotnet
      BuildFrameWorks: netstandard2.0


before_build:
  - $(asNuget) restore

build:
    project: CoAP.Std10.sln
